### ISSUE TITLE
Feature Request: Ability to export as image

### ISSUE THREAD

**Issue by erbanku** [crashmax-dev/twallpaper#6]
Thanks for making this; It is awesome, but I think we can make it even further; I think it is nice to have the "Export as image" ability for general use cases, thanks.

**Comment by crashmax-dev** [comment]
@erbanku Hi, I don't think the library should have an image export function, its purpose is to render animation.
I am currently working on an example [export-as-image](https://github.com/crashmax-dev/twallpaper/pull/7) :eyes:

**Comment by crashmax-dev** [comment]
[export-as-image](https://github.com/crashmax-dev/twallpaper/blob/master/examples/export-as-image/src/index.ts) merged
